- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
   - name: install nginx server
     ansible.builtin.package:
       name: nginx
       state: present
    
   - name: start nginx server
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
  
   - name: remove the default content in html
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent
  
   - name: create the custom html directory
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: directory

   - name: download the frontend code
     ansible.builtin.get_url:
       url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
       dest: /tmp/frontend.zip

   - name: extract the file
     ansible.builtin.unarchive:
       src: /tmp/frontend.zip
       dest: /usr/share/nginx/html
       remote_src: yes  #This section will execute in remote server and not Ansible server

   - name: copy the conf file 
     ansible.builtin.copy:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf
    
   - name: restart nginx
     ansible.builtin.service:
      name: nginx
      state: restarted
